[GenesisDoc]
  GenesisTime = 2018-08-22T18:39:33Z
  ChainName = "BurrowChain_016017"
  [GenesisDoc.GlobalPermissions]
    [GenesisDoc.GlobalPermissions.Base]
      Perms = 2302
      SetBit = 16383

  [[GenesisDoc.Accounts]]
    Address = "6D1BD5D6C7CA7EDEC608E79234E7292488CEAF82"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"A318CF5E5299AC8CF7E745BD399C49F315E9A790AD1E30B5A3F708780B33C5C0\"}"
    Amount = 99999999999999
    Name = "Full_0"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = 16383
        SetBit = 16383

  [[GenesisDoc.Accounts]]
    Address = "543EC95EE288F7DB2D759E7F28712E8AB2E89650"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"8A7DAF4F5E20D2E64C7F41F4ECF6E6B1BE6A6046A377BA0568EE1AD325D90698\"}"
    Amount = 9999999999
    Name = "Participant_0"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = 2118
        SetBit = 2118

  [[GenesisDoc.Validators]]
    Address = "6D1BD5D6C7CA7EDEC608E79234E7292488CEAF82"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"A318CF5E5299AC8CF7E745BD399C49F315E9A790AD1E30B5A3F708780B33C5C0\"}"
    Amount = 9999999999
    Name = "Full_0"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "6D1BD5D6C7CA7EDEC608E79234E7292488CEAF82"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"A318CF5E5299AC8CF7E745BD399C49F315E9A790AD1E30B5A3F708780B33C5C0\"}"
      Amount = 9999999999

[Tendermint]
  Seeds = ""
  SeedMode = false
  PersistentPeers = ""
  ListenAddress = "tcp://0.0.0.0:26656"
  ExternalAddress = ""
  Moniker = ""
  TendermintRoot = ".burrow"

[Execution]

[Keys]
  GRPCServiceEnabled = true
  AllowBadFilePermissions = false
  RemoteAddress = ""
  KeysDirectory = ".keys"

[RPC]
  [RPC.Info]
    Enabled = true
    ListenAddress = "tcp://127.0.0.1:26658"
  [RPC.Profiler]
    Enabled = false
    ListenAddress = "tcp://127.0.0.1:6060"
  [RPC.GRPC]
    Enabled = true
    ListenAddress = "127.0.0.1:10997"
  [RPC.Metrics]
    Enabled = false
    ListenAddress = "tcp://127.0.0.1:9102"
    MetricsPath = "/metrics"
    BlockSampleSize = 100

[Logging]
  ExcludeTrace = false
  NonBlocking = false
  [Logging.RootSink]
    [Logging.RootSink.Output]
      OutputType = "stderr"
      Format = "json"

